"""EHealthWave fix db relations ship

Revision ID: 150676a23451
Revises: 
Create Date: 2024-09-06 21:19:07.198946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150676a23451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('patient', 'doctor'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('banner_picture', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_banner_picture'), ['banner_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_bio'), ['bio'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_qualification'), ['qualification'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_zip_code'), ['zip_code'], unique=False)

    op.create_table('messages',
    sa.Column('message_id', sa.String(length=60), nullable=False),
    sa.Column('sender_id', sa.String(length=60), nullable=True),
    sa.Column('receiver_id', sa.String(length=60), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('notification_message', sa.String(length=255), nullable=True),
    sa.Column('notification_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_notification_message'), ['notification_message'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_url'), ['notification_url'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('about_me', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('banner_picture', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_about_me'), ['about_me'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_banner_picture'), ['banner_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_zip_code'), ['zip_code'], unique=False)

    op.create_table('posts',
    sa.Column('post_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('post', sa.String(length=255), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('post_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_post'), ['post'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_url'), ['post_url'], unique=False)

    op.create_table('user_ip',
    sa.Column('user_ip_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('user_ip', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_ip_id')
    )
    with op.batch_alter_table('user_ip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ip_user_ip'), ['user_ip'], unique=False)

    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=60), nullable=False),
    sa.Column('patient_id', sa.String(length=60), nullable=True),
    sa.Column('doctor_id', sa.String(length=60), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('appointment_time', sa.String(length=10), nullable=True),
    sa.Column('appointment_type', sa.Enum('in-person', 'telemedicine'), nullable=True),
    sa.Column('appointment_status', sa.Enum('scheduled', 'cancelled', 'completed'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointment_time'), ['appointment_time'], unique=False)

    op.create_table('certificates',
    sa.Column('certificate_id', sa.String(length=60), nullable=False),
    sa.Column('doctor_id', sa.String(length=60), nullable=True),
    sa.Column('certificate_name', sa.String(length=100), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_certificate_name'), ['certificate_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_certificate_number'), ['certificate_number'], unique=False)

    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=60), nullable=False),
    sa.Column('post_id', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment'), ['comment'], unique=False)

    op.create_table('documents',
    sa.Column('document_id', sa.String(length=60), nullable=False),
    sa.Column('patient_id', sa.String(length=60), nullable=True),
    sa.Column('doctor_id', sa.String(length=60), nullable=True),
    sa.Column('document_name', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=160), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_document_name'), ['document_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_url'), ['document_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_picture'), ['picture'], unique=False)

    op.create_table('medical_history',
    sa.Column('medical_history_id', sa.String(length=60), nullable=False),
    sa.Column('patient_id', sa.String(length=60), nullable=True),
    sa.Column('doctor_id', sa.String(length=60), nullable=True),
    sa.Column('medical_history_name', sa.String(length=100), nullable=True),
    sa.Column('medical_history_type', sa.String(length=50), nullable=True),
    sa.Column('medical_history_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('medical_history_id')
    )
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_history_medical_history_name'), ['medical_history_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_medical_history_type'), ['medical_history_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_medical_history_url'), ['medical_history_url'], unique=False)

    op.create_table('post_likes',
    sa.Column('post_like_id', sa.String(length=60), nullable=False),
    sa.Column('post_id', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('post_like_id')
    )
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.String(length=60), nullable=False),
    sa.Column('patient_id', sa.String(length=60), nullable=True),
    sa.Column('doctor_id', sa.String(length=60), nullable=True),
    sa.Column('prescription_name', sa.String(length=100), nullable=True),
    sa.Column('prescription_type', sa.String(length=50), nullable=True),
    sa.Column('prescription_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_prescription_name'), ['prescription_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_prescription_type'), ['prescription_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_prescription_url'), ['prescription_url'], unique=False)

    op.create_table('comment_likes',
    sa.Column('comment_like_id', sa.String(length=60), nullable=False),
    sa.Column('comment_id', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescription_url'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescription_type'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescription_name'))

    op.drop_table('prescriptions')
    op.drop_table('post_likes')
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_history_medical_history_url'))
        batch_op.drop_index(batch_op.f('ix_medical_history_medical_history_type'))
        batch_op.drop_index(batch_op.f('ix_medical_history_medical_history_name'))

    op.drop_table('medical_history')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_picture'))
        batch_op.drop_index(batch_op.f('ix_documents_document_url'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_document_name'))

    op.drop_table('documents')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comment'))

    op.drop_table('comments')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_certificate_number'))
        batch_op.drop_index(batch_op.f('ix_certificates_certificate_name'))

    op.drop_table('certificates')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_time'))

    op.drop_table('appointments')
    with op.batch_alter_table('user_ip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ip_user_ip'))

    op.drop_table('user_ip')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_post_url'))
        batch_op.drop_index(batch_op.f('ix_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_posts_post'))

    op.drop_table('posts')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_zip_code'))
        batch_op.drop_index(batch_op.f('ix_patients_state'))
        batch_op.drop_index(batch_op.f('ix_patients_profile_picture'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_middle_name'))
        batch_op.drop_index(batch_op.f('ix_patients_last_name'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index(batch_op.f('ix_patients_city'))
        batch_op.drop_index(batch_op.f('ix_patients_banner_picture'))
        batch_op.drop_index(batch_op.f('ix_patients_address'))
        batch_op.drop_index(batch_op.f('ix_patients_about_me'))

    op.drop_table('patients')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_notification_url'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_message'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_messages_message'))

    op.drop_table('messages')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_zip_code'))
        batch_op.drop_index(batch_op.f('ix_doctors_state'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))
        batch_op.drop_index(batch_op.f('ix_doctors_qualification'))
        batch_op.drop_index(batch_op.f('ix_doctors_profile_picture'))
        batch_op.drop_index(batch_op.f('ix_doctors_phone'))
        batch_op.drop_index(batch_op.f('ix_doctors_middle_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_license_number'))
        batch_op.drop_index(batch_op.f('ix_doctors_last_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_first_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_email'))
        batch_op.drop_index(batch_op.f('ix_doctors_city'))
        batch_op.drop_index(batch_op.f('ix_doctors_bio'))
        batch_op.drop_index(batch_op.f('ix_doctors_banner_picture'))
        batch_op.drop_index(batch_op.f('ix_doctors_address'))

    op.drop_table('doctors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
