"""EHealthWave fix db relations ship

Revision ID: f159f1a2b2a5
Revises: 
Create Date: 2024-09-06 21:36:47.900494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f159f1a2b2a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('patient', 'doctor'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('banner_picture', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_banner_picture'), ['banner_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_bio'), ['bio'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_qualification'), ['qualification'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_zip_code'), ['zip_code'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('about_me', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('banner_picture', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_about_me'), ['about_me'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_banner_picture'), ['banner_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_zip_code'), ['zip_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_zip_code'))
        batch_op.drop_index(batch_op.f('ix_patients_state'))
        batch_op.drop_index(batch_op.f('ix_patients_profile_picture'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_middle_name'))
        batch_op.drop_index(batch_op.f('ix_patients_last_name'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index(batch_op.f('ix_patients_city'))
        batch_op.drop_index(batch_op.f('ix_patients_banner_picture'))
        batch_op.drop_index(batch_op.f('ix_patients_address'))
        batch_op.drop_index(batch_op.f('ix_patients_about_me'))

    op.drop_table('patients')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_zip_code'))
        batch_op.drop_index(batch_op.f('ix_doctors_state'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))
        batch_op.drop_index(batch_op.f('ix_doctors_qualification'))
        batch_op.drop_index(batch_op.f('ix_doctors_profile_picture'))
        batch_op.drop_index(batch_op.f('ix_doctors_phone'))
        batch_op.drop_index(batch_op.f('ix_doctors_middle_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_license_number'))
        batch_op.drop_index(batch_op.f('ix_doctors_last_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_first_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_email'))
        batch_op.drop_index(batch_op.f('ix_doctors_city'))
        batch_op.drop_index(batch_op.f('ix_doctors_bio'))
        batch_op.drop_index(batch_op.f('ix_doctors_banner_picture'))
        batch_op.drop_index(batch_op.f('ix_doctors_address'))

    op.drop_table('doctors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
